package com.kerbart.checkpoint.controller.responses;

public enum ErrorCode {
    USER_BAD_CREDENTIALS, //
    USER_ALREADY_EXISTS, //
    USER_UNKONWN, //
    USER_TOKEN_UNKNOWN,//
    USER_DOES_KNOW_HAVE_THIS_APPLICATION, //
    USER_ALREADY_HAVE_THIS_APPLICATION, //
    USER_CREATION_ERROR, //
    APPLICATION_UNKNOWN, //
    PATIENT_UNKNOWN, //
    FILE_UPLOAD_ERROR
}
